[package]
name = "aoc2023"
version = "0.1.0"
edition = "2021"

[features]
default = []
day1 = []
day2 = []
day3 = []
day4 = []
day5 = []
day6 = []
day7 = []
day8 = []
day9 = []
day10 = []
benchmark = []
debug = []

[dependencies]
rayon = "1.8.0"
